# Generated by Django 6.0 on 2026-03-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20, verbose_name='Canal de Comunicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workflows.customerworkflow', verbose_name='Proceso del Cliente')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante (Del cliente)'), ('outbound', 'Saliente (Hacia el cliente)')], max_length=15, verbose_name='Dirección')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto')),
                ('body', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('from_address', models.CharField(max_length=255, verbose_name='De (Remitente / Teléfono)')),
                ('to_address', models.CharField(max_length=255, verbose_name='Para (Destinatario / Teléfono)')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='ID del Proveedor (SendGrid/Meta)')),
                ('in_reply_to', models.CharField(blank=True, max_length=255, verbose_name='En respuesta a (ID)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('error', 'Error de envío')], default='draft', max_length=15, verbose_name='Estado')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata Omnicanal')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Recibido el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation', verbose_name='Hilo de Conversación')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.message', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
            },
        ),
    ]
