# Generated by Django 6.0 on 2026-03-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Dirección de Correo (Ej: ventas@marca.com)')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Host SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('smtp_username', models.CharField(max_length=255, verbose_name='Usuario SMTP')),
                ('smtp_password', models.CharField(max_length=500, verbose_name='Contraseña SMTP (Encriptada)')),
                ('use_tls', models.BooleanField(default=True)),
                ('imap_host', models.CharField(max_length=255, verbose_name='Host IMAP')),
                ('imap_port', models.IntegerField(default=993, verbose_name='Puerto IMAP')),
                ('imap_username', models.CharField(max_length=255, verbose_name='Usuario IMAP')),
                ('imap_password', models.CharField(max_length=500, verbose_name='Contraseña IMAP (Encriptada)')),
                ('use_ssl', models.BooleanField(default=True)),
                ('daily_send_limit', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_configs', to='core.brand')),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'unique_together': {('brand', 'email_address')},
            },
        ),
    ]
