# Generated by Django 6.0 on 2026-05-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailconfiguration'),
        ('documents', '0002_document_checksum_document_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='documents.document', verbose_name='Documento Físico'),
        ),
    ]
