# Generated by Django 6.0 on 2026-03-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre Comercial'),
        ),
        migrations.CreateModel(
            name='BrandLegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='RUC / ID Fiscal')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('fiscal_address', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='core.brand')),
            ],
            options={
                'verbose_name': 'Brand Legal Profile',
                'verbose_name_plural': 'Brand Legal Profiles',
            },
        ),
    ]
