# Generated by Django 6.0 on 2026-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brand_name_brandlegalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandlegalprofile',
            name='tax_id',
            field=models.CharField(max_length=50, verbose_name='RUC / ID Fiscal'),
        ),
    ]
