# Generated by Django 6.0 on 2026-04-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brandlegalprofile_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='RUC / ID Fiscal')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('fiscal_address', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='core.legalentity'),
        ),
        migrations.DeleteModel(
            name='BrandLegalProfile',
        ),
    ]
