# Generated by Django 6.0 on 2026-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('AUTH_LOGIN', 'Inicio de sesión exitoso'), ('AUTH_FAILED', 'Intento de sesión fallido'), ('USER_INVITED', 'Usuario invitado a la marca'), ('ROLE_CHANGED', 'Rol de usuario modificado'), ('USER_DEACTIVATED', 'Usuario desactivado'), ('PASSWORD_CHANGED', 'Contraseña actualizada'), ('PROFILE_UPDATED', 'Perfil de usuario actualizado')], db_index=True, max_length=50),
        ),
    ]
