# Generated by Django 6.0 on 2026-03-17 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código (Ej: trade, billing)')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Proceso')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('sender_email', models.EmailField(blank=True, help_text='Ej: "Ventas <ventas@marca.com>"', max_length=254, null=True)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Ej: "ventas@marca.com"', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.brand')),
                ('permissions', models.ManyToManyField(blank=True, related_name='workflows', to='core.permission', verbose_name='Permisos requeridos')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['sort_order'],
                'unique_together': {('brand', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CustomerWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado el')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado el')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_workflows', to='customers.customer', verbose_name='Cliente')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_instances', to='workflows.workflow', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Customer Workflow',
                'verbose_name_plural': 'Customer Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código (Ej: pending, approved)')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden cronológico')),
                ('is_final', models.BooleanField(default=False, help_text='Marcar si este estado finaliza el proceso (Ej: Completado, Rechazado)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.workflow', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Workflow State',
                'verbose_name_plural': 'Workflow States',
                'ordering': ['workflow', 'sort_order'],
                'unique_together': {('workflow', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CustomerWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario / Motivo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('customer_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='workflows.customerworkflow', verbose_name='Proceso del Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workflows.workflowstate', verbose_name='Estado Registrado')),
            ],
            options={
                'verbose_name': 'Workflow History Log',
                'verbose_name_plural': 'Workflow History Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='customerworkflow',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_customers', to='workflows.workflowstate', verbose_name='Estado Actual'),
        ),
        migrations.AddConstraint(
            model_name='customerworkflow',
            constraint=models.UniqueConstraint(fields=('customer', 'workflow', 'finished_at'), name='unique_active_workflow_per_customer'),
        ),
    ]
