# Generated by Django 6.0 on 2026-03-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailconfiguration'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='reply_to_email',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='sender_email',
        ),
        migrations.AddField(
            model_name='workflow',
            name='email_config',
            field=models.ForeignKey(blank=True, help_text='Bandeja de correo usada para enviar/recibir en este proceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to='communications.emailconfiguration'),
        ),
    ]
