# Generated by Django 6.0 on 2026-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_remove_workflow_reply_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerworkflow',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Contexto actual del flujo (ej. plan negociado, montos, credenciales)', verbose_name='Datos Comerciales Vivos'),
        ),
    ]
