# Generated by Django 6.0 on 2026-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Dispositivo/Navegador'),
        ),
    ]
