# Generated by Django 6.0 on 2026-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_last_ip_userprofile_last_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PASSPORT', 'Pasaporte'), ('RUC', 'RUC (Persona Natural)')], max_length=20, null=True, verbose_name='Tipo de Doc.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero de Documento'),
        ),
    ]
