# Generated by Django 6.0 on 2026-02-02 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.SlugField()),
                ('schema', models.JSONField()),
                ('version', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='core.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('brand', 'form_key', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FormularioEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payload', models.JSONField()),
                ('source', models.CharField(choices=[('widget', 'Widget'), ('interno', 'Interno'), ('api', 'API')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='form_engine.formulario')),
            ],
        ),
    ]
