# Generated by Django 6.0 on 2026-03-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='schema',
            new_name='structure',
        ),
    ]
