# Generated by Django 6.0 on 2026-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_engine', '0002_rename_schema_form_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='source',
            field=models.CharField(choices=[('widget', 'Widget'), ('iframe', 'Iframe HTML'), ('internal', 'Internal'), ('api', 'API')], max_length=20),
        ),
    ]
