# Generated by Django 6.0 on 2026-04-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_engine', '0003_alter_formsubmission_source'),
        ('workflows', '0002_remove_workflow_reply_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='target_workflow',
            field=models.ForeignKey(blank=True, help_text='¿A qué flujo se enviarán los datos? (Por defecto: Comercial)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_forms', to='workflows.workflow'),
        ),
    ]
