# Generated by Django 6.0 on 2026-04-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_engine', '0004_form_target_workflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkflowForm',
        ),
    ]
