# Generated by Django 6.0 on 2026-03-17 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=20, verbose_name='RUC / Identificación Fiscal')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('fiscal_address', models.CharField(blank=True, max_length=255, verbose_name='Domicilio Fiscal')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Datos Extra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.brand')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'unique_together': {('brand', 'tax_id')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='¿Es contacto principal?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.brand')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('B2B', 'Empresa (B2B)'), ('B2C', 'Individuo (B2C)')], default='B2B', max_length=3, verbose_name='Tipo de Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.brand', verbose_name='Marca')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='customers.company', verbose_name='Empresa Asociada')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='customers.contact', verbose_name='Contacto Asociado')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'unique_together': {('brand', 'company')},
            },
        ),
    ]
